# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel, QGridLayout
from Scanner_Class import scanner
from Parser import parser, Token
from PyQt5.QtGui import QPixmap



class Ui_MainWindow(object):
    def checkForidentifierError(self, listOfAllstrings,tokenValuesList, tokentypes):
        f = open("Output.txt", "w")
        count = 0
        copy_listOfAllstrings = listOfAllstrings
        for i in tokenValuesList:   #[read, 1f,read,1f] i=1f
            if (i[0].isalpha() == False) and (i[0] != '_') and (i[-1].isalpha()):

                for j in range(len(listOfAllstrings)):

                    if i in copy_listOfAllstrings[j]:
                       count = count + 1
                       copy_listOfAllstrings[j]=copy_listOfAllstrings[j].replace(i,'')
                       error = f"error {count} , in line {j + 1}\n    Invalid Syntax! ({i})\n"
                       self.textBrowser.setStyleSheet("background-color:rgb(255,255,255);\n"
                                                       "color:rgb(200,0,0);")
                       self.textBrowser.append(error)
                        # f.write(f"error {count} , in line {j + 1}\n    Invalid Syntax! ({i})\n")

        if (count == 0):
            i = 1
            self.textBrowser.setStyleSheet("background-color:rgb(255,255,255);\n"
                                           "color:rgb(0,200,0);")
            self.textBrowser.append(f"Scanning Successful! , 0 Errors found")
            for RowNumber in range(len(tokenValuesList)):
                self.tableWidget.insertRow(RowNumber)
                item1 = QtWidgets.QTableWidgetItem(tokenValuesList[RowNumber])
                item2 = QtWidgets.QTableWidgetItem(tokentypes[RowNumber])
                item1.setTextAlignment(QtCore.Qt.AlignHCenter)
                item2.setTextAlignment(QtCore.Qt.AlignHCenter)
                self.tableWidget.setItem(RowNumber, 0, item1)
                self.tableWidget.setItem(RowNumber, 1, item2)
                if i < len(tokenValuesList):
                    i = i + 1
            for j in range(len(tokenValuesList)):
                f.write(f"{tokenValuesList[j]}")
                f.write(',')
                f.write(f"{tokentypes[j]}\n")
        else:
            self.textBrowser.setStyleSheet("background-color:rgb(255,255,255);\n"
                                           "color:rgb(200,0,0);")
            self.textBrowser.append(f"Scanning Failed! , {count} errors found")
        f.close()


    def SCanButton_function(self):
        program = self.textEdit.toPlainText()
        infile = open('Input.txt', "w")
        infile.write(program)
        infile.close()
        a = scanner('Input.txt')
        listofstrings = a.readTheFile()
        listOfTokens = a.getAllTokens(listofstrings)
        tokentypes = a.getTokenTypes(listOfTokens)
        self.tableWidget.setRowCount(0)
        self.textBrowser.clear()
        self.checkForidentifierError(listofstrings,listOfTokens,tokentypes)


    def ParseButton_function(self):
        p=parser()
        p.parse_stmt_sequence()
        self.photo.setPixmap(QtGui.QPixmap("parser_syntax_tree.png"))
        self.photo.setScaledContents(True)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 340)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: rgb(25, 51, 37);\n"
"border-top-color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.tabWidget.setIconSize(QtCore.QSize(20, 12))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(67, 67, 67);\n"
"color:rgb(255,255,255);")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setFontPointSize(10)
        self.horizontalLayout.addWidget(self.textEdit)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(67, 67, 67);\n"
"color:rgb(255,255,255);")
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(36, 73, 54);\n"
"border-color: rgb(32, 64, 47);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(47, 149, 110))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(47, 149, 110))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(320)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(34)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(22)
        self.tableWidget.verticalHeader().setMinimumSectionSize(22)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setStyleSheet("background-color: rgb(47, 149, 110);\n"
                                      
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.SCanButton_function)
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setStyleSheet("background-color: rgb(47, 149, 110);\n"
                                        "font: 75 12pt \"MS Shell Dlg 2\";\n"
                                        "color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.ParseButton_function)
        self.verticalLayout.addWidget(self.pushButton_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(67, 67, 67);\n"
"color:rgb(255,255,255);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser.setStyleSheet("font: 1 1pt \"MS Shell Dlg 2\";\n"
                                       "background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setFontPointSize(15)


        self.horizontalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.verticalLayout.setStretch(0, 15)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.photo = QtWidgets.QLabel(self.tab_2)
        self.photo.setObjectName("photo")
        self.horizontalLayout_7.addWidget(self.photo)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
       # self.setFixedSize(self.layout.sizeHint())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Compiler"))
        self.groupBox.setTitle(_translate("MainWindow", "Program"))
        self.groupBox_2.setTitle(_translate("MainWindow", "TokenList"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Token_Value"))
        stylesheet = "::section{Background-color:rgb(47,149,110);}"
        self.tableWidget.horizontalHeader().setStyleSheet(stylesheet)

        #self.tableWidget.setHorizontalHeaderItem(0, item)
        item = self.tableWidget.horizontalHeaderItem(1)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item.setText(_translate("MainWindow", "Token_Type"))
        self.pushButton.setText(_translate("MainWindow", "Scan"))
        self.pushButton_2.setText(_translate("MainWindow", "Parse"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Console"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Scanner"))
        self.photo.setText(_translate("MainWindow", "syntax tree"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Parse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.setMinimumSize(1200,700)
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
